#################################
#          基础透明配置           #
#      优化稳定性,避免卡顿        #
#################################

backend = "xrender";
vsync = true;

use-damage = true;

xrender-sync-fence = true;

unredir-if-possible = false;

detect-transient = true;
detect-client-leader = true;

fading = false;

inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;

opacity-rule = [
    "100:class_g = 'Alacritty'",
    "100:class_g = 'xfce4-terminal'",
    "100:class_g = 'Xfce4-terminal'",
    "100:class_g = 'code-oss'",
    "100:class_g = 'Code'",
    "100:class_g = 'TelegramDesktop'",
    "100:class_g = 'Nemo'",
    "100:class_g = 'nemo'"
];

shadow-exclude = [
    "class_g = 'Nemo'",
    "class_g = 'nemo'"
];

corner-radius = 0;

wintypes:
{
  tooltip = { fade = false; shadow = false; opacity = 0.85; focus = true; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1; }
  dropdown_menu = { opacity = 1; }
  normal = { shadow = false; };
  dialog = { shadow = false; };
  Nemo = { shadow = false; fade = false; };
};
